# Generated by Django 4.2.2 on 2023-10-12 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HourlyWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('temp', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('wind_dir', models.FloatField()),
                ('wind_gust', models.FloatField()),
                ('precipitation', models.FloatField()),
                ('weather_symbol', models.IntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.location')),
            ],
        ),
        migrations.CreateModel(
            name='DailyWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temp_max', models.FloatField()),
                ('temp_min', models.FloatField()),
                ('wind_gust', models.FloatField()),
                ('precipitation', models.FloatField()),
                ('weather_symbol', models.IntegerField()),
                ('sea_pressure', models.FloatField()),
                ('uv_index', models.FloatField()),
                ('sunrise', models.DateTimeField()),
                ('sunset', models.DateTimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.location')),
            ],
        ),
    ]
