# Generated by Django 4.2.2 on 2023-10-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyweather',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
